name: sboxproject
services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ../reverse-proxy/domains:/etc/nginx/conf.d/
      - ../reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../reverse-proxy/log:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
    networks:
      app-network:
        ipv4_address: 172.18.0.2

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    image: sbox-backend
    container_name: backend
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: my_database    
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    depends_on:
      - db
    networks:
      app-network:
        ipv4_address: 172.18.0.5

  front-end:   
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    image: sbox-frontend
    container_name: frontend
    ports:
      - "8001:8000"
    volumes:
      - ../frontend:/app
    networks:
      app-network:
        ipv4_address: 172.18.0.3

  db:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d my_database "]
      interval: 5s
      retries: 5
    networks:
      app-network:
        ipv4_address: 172.18.0.4

volumes:
  db_data:

networks:
  app-network:
    name: maturita_app-network
    external: true